package com.testshaper.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * Stores chunks of text extracted from curriculum documents for RAG processing.
 */
@Entity
@Table(name = "curriculum_document_chunks", indexes = {
    @Index(name = "idx_doc_id", columnList = "document_id")
})
@Getter
@Setter
public class CurriculumDocumentChunk extends BaseTenantEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "document_id")
    private CurriculumDocument document; // Optional: If chunk comes from raw Document

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "source_book_id")
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties({"pages", "indices", "extractionJobs", "questionGenerationJobs", "topicExtractionJobs", "documentChunks"})
    private SourceBookMaster sourceBook; // Optional: If chunk comes from Textbook/Guidebook

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "source_book_index_id")
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties({"sourceBook"})
    private SourceBookIndex sourceBookIndex; // Maps back to the book's specific TOC element

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "topic_id")
    private Topic mappedTopic; // The curriculum topic this chunk belongs to

    @Column(name = "chunk_text", columnDefinition = "LONGTEXT", nullable = false)
    private String chunkText;

    @Column(name = "page_number")
    private Integer pageNumber;

    @Column(name = "image_url", length = 1000)
    private String imageUrl; // For storing diagram/stem image URLs

    @Column(name = "is_vision_extracted")
    private Boolean isVisionExtracted = false; // Indicates if this chunk was generated by Gemini Multimodal OCR

    @Column(name = "chunk_index")
    private Integer chunkIndex;

    @Column(name = "token_count")
    private Integer tokenCount;

    @Column(name = "metadata", columnDefinition = "TEXT")
    private String metadata; // Stores JSON string of extracted source metadata (e.g. board, year, school)
}
